name: Test Secret

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Test Secret
        run: |
          if [ -n "${{ secrets.SHOPIFY_TEST_TOKEN }}" ]; then
            echo "SHOPIFY_TEST_TOKEN is set (length: ${#SHOPIFY_TEST_TOKEN})"
          else
            echo "SHOPIFY_TEST_TOKEN is not set"
          fi 